<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

/*
|--------------------------------------------------------------------------
| Base Site URL
|--------------------------------------------------------------------------
|
| URL to your CodeIgniter root. Typically this will be your base URL,
| WITH a trailing slash:
|
|	http://example.com/
|
| If this is not set then CodeIgniter will guess the protocol, domain and
| path to your installation.
|
*/
// Dynamic base URL resolution.
//
// Priority order:
//   1. For real HTTP requests, derive base_url from the actual request
//      ($_SERVER['HTTP_HOST'] + scheme + script path). This guarantees that
//      the same install works correctly via http://localhost/hms-master/ AND
//      http://<LAN-IP>/hms-master/ without breaking assets, AJAX, or links.
//   2. For CLI / cron / non-HTTP contexts, use APP_BASE_URL (Apache SetEnv
//      or .env via index.php loader).
//   3. Fall back to a safe localhost default.
//
// This protects against the LAN-deployment trap where setting
// APP_BASE_URL=http://<LAN-IP>/hms-master/ silently breaks localhost access
// because all CSS/JS/anchor URLs would be hard-pinned to the LAN IP.
if (!empty($_SERVER['HTTP_HOST'])) {
    $isHttps = (
        (!empty($_SERVER['HTTPS']) && strtolower($_SERVER['HTTPS']) !== 'off')
        || (!empty($_SERVER['HTTP_X_FORWARDED_PROTO']) && strtolower($_SERVER['HTTP_X_FORWARDED_PROTO']) === 'https')
        || (!empty($_SERVER['SERVER_PORT']) && (int)$_SERVER['SERVER_PORT'] === 443)
    );
    $scheme = $isHttps ? 'https' : 'http';
    $host = $_SERVER['HTTP_HOST'];
    // Derive install path from SCRIPT_NAME (e.g. "/hms-master/index.php" -> "/hms-master/")
    $scriptName = isset($_SERVER['SCRIPT_NAME']) ? $_SERVER['SCRIPT_NAME'] : '/index.php';
    $installPath = rtrim(str_replace('\\', '/', dirname($scriptName)), '/') . '/';
    if ($installPath === '' || $installPath === '//') { $installPath = '/'; }
    $config['base_url'] = $scheme . '://' . $host . $installPath;
} elseif (getenv('APP_BASE_URL') !== false && getenv('APP_BASE_URL') !== '') {
    $config['base_url'] = rtrim(getenv('APP_BASE_URL'), '/') . '/';
} else {
    $config['base_url'] = 'http://localhost/hms-master/';
}

/*
|--------------------------------------------------------------------------
| Index File
|--------------------------------------------------------------------------
|
| Typically this will be your index.php file, unless you've renamed it to
| something else. If you are using mod_rewrite to remove the page set this
| variable so that it is blank.
|
*/
$config['index_page'] = '';

/*
|--------------------------------------------------------------------------
| URI PROTOCOL
|--------------------------------------------------------------------------
|
| This item determines which server global should be used to retrieve the
| URI string.  The default setting of 'AUTO' works for most servers.
| If your links do not seem to work, try one of the other delicious flavors:
|
| 'AUTO'			Default - auto detects
| 'PATH_INFO'		Uses the PATH_INFO
| 'QUERY_STRING'	Uses the QUERY_STRING
| 'REQUEST_URI'		Uses the REQUEST_URI
| 'ORIG_PATH_INFO'	Uses the ORIG_PATH_INFO
|
*/
$config['uri_protocol']	= 'AUTO';

/*
|--------------------------------------------------------------------------
| URL suffix
|--------------------------------------------------------------------------
|
| This option allows you to add a suffix to all URLs generated by CodeIgniter.
| For more information please see the user guide:
|
| http://codeigniter.com/user_guide/general/urls.html
*/

$config['url_suffix'] = '';

/*
|--------------------------------------------------------------------------
| Default Language
|--------------------------------------------------------------------------
|
| This determines which set of language files should be used. Make sure
| there is an available translation if you intend to use something other
| than english.
|
*/
$config['language']	= 'english';

/*
|--------------------------------------------------------------------------
| Default Character Set
|--------------------------------------------------------------------------
|
| This determines which character set is used by default in various methods
| that require a character set to be provided.
|
*/
$config['charset'] = 'UTF-8';

/*
|--------------------------------------------------------------------------
| Enable/Disable System Hooks
|--------------------------------------------------------------------------
|
| If you would like to use the 'hooks' feature you must enable it by
| setting this variable to TRUE (boolean).  See the user guide for details.
|
*/
$config['enable_hooks'] = TRUE;


/*
|--------------------------------------------------------------------------
| Class Extension Prefix
|--------------------------------------------------------------------------
|
| This item allows you to set the filename/classname prefix when extending
| native libraries.  For more information please see the user guide:
|
| http://codeigniter.com/user_guide/general/core_classes.html
| http://codeigniter.com/user_guide/general/creating_libraries.html
|
*/
$config['subclass_prefix'] = 'MY_';


/*
|--------------------------------------------------------------------------
| Allowed URL Characters
|--------------------------------------------------------------------------
|
| This lets you specify with a regular expression which characters are permitted
| within your URLs.  When someone tries to submit a URL with disallowed
| characters they will get a warning message.
|
| As a security measure you are STRONGLY encouraged to restrict URLs to
| as few characters as possible.  By default only these are allowed: a-z 0-9~%.:_-
|
| Leave blank to allow all characters -- but only if you are insane.
|
| DO NOT CHANGE THIS UNLESS YOU FULLY UNDERSTAND THE REPERCUSSIONS!!
|
*/
$config['permitted_uri_chars'] = 'a-z 0-9~%.:_\-@\()';


/*
|--------------------------------------------------------------------------
| Enable Query Strings
|--------------------------------------------------------------------------
|
| By default CodeIgniter uses search-engine friendly segment based URLs:
| example.com/who/what/where/
|
| By default CodeIgniter enables access to the $_GET array.  If for some
| reason you would like to disable it, set 'allow_get_array' to FALSE.
|
| You can optionally enable standard query string based URLs:
| example.com?who=me&what=something&where=here
|
| Options are: TRUE or FALSE (boolean)
|
| The other items let you set the query string 'words' that will
| invoke your controllers and its functions:
| example.com/index.php?c=controller&m=function
|
| Please note that some of the helpers won't work as expected when
| this feature is enabled, since CodeIgniter is designed primarily to
| use segment based URLs.
|
*/
$config['allow_get_array']		= TRUE;
$config['enable_query_strings'] = FALSE;
$config['controller_trigger']	= 'c';
$config['function_trigger']		= 'm';
$config['directory_trigger']	= 'd'; // experimental not currently in use

/*
|--------------------------------------------------------------------------
| Error Logging Threshold
|--------------------------------------------------------------------------
|
| If you have enabled error logging, you can set an error threshold to
| determine what gets logged. Threshold options are:
| You can enable error logging by setting a threshold over zero. The
| threshold determines what gets logged. Threshold options are:
|
|	0 = Disables logging, Error logging TURNED OFF
|	1 = Error Messages (including PHP errors)
|	2 = Debug Messages
|	3 = Informational Messages
|	4 = All Messages
|
| For a live site you'll usually only enable Errors (1) to be logged otherwise
| your log files will fill up very fast.
|
*/
$perfLog = (getenv('PERF_LOG') === '1');
$config['log_threshold'] = (ENVIRONMENT === 'production') ? ($perfLog ? 2 : 1) : 2;

/*
|--------------------------------------------------------------------------
| Error Logging Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| application/logs/ folder. Use a full server path with trailing slash.
|
*/
$config['log_path'] = '';

/*
|--------------------------------------------------------------------------
| Date Format for Logs
|--------------------------------------------------------------------------
|
| Each item that is logged has an associated date. You can use PHP date
| codes to set your own date formatting
|
*/
$config['log_date_format'] = 'Y-m-d H:i:s';

/*
|--------------------------------------------------------------------------
| Cache Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| system/cache/ folder.  Use a full server path with trailing slash.
|
*/
$config['cache_path'] = '';

/*
|--------------------------------------------------------------------------
| Encryption Key
|--------------------------------------------------------------------------
|
| If you use the Encryption class or the Session class you
| MUST set an encryption key.  See the user guide for info.
|
*/
$config['encryption_key'] = 'YmahBYw10KfzhxWb3YpuX057HnGVR1Xi';

/*
|--------------------------------------------------------------------------
| Session Variables
|--------------------------------------------------------------------------
|
| 'sess_cookie_name'		= the name you want for the cookie
| 'sess_expiration'			= the number of SECONDS you want the session to last.
|   by default sessions last 7200 seconds (two hours).  Set to zero for no expiration.
| 'sess_expire_on_close'	= Whether to cause the session to expire automatically
|   when the browser window is closed
| 'sess_encrypt_cookie'		= Whether to encrypt the cookie
| 'sess_use_database'		= Whether to save the session data to a database
| 'sess_table_name'			= The name of the session database table
| 'sess_match_ip'			= Whether to match the user's IP address when reading the session data
| 'sess_match_useragent'	= Whether to match the User Agent when reading the session data
| 'sess_time_to_update'		= how many seconds between CI refreshing Session Information
|
*/
$config['sess_cookie_name']		= 'hms_session';
$config['sess_expiration']		= 7200;
$config['sess_expire_on_close']	= TRUE;
$config['sess_encrypt_cookie']	= TRUE;
$config['sess_use_database']	= TRUE;
$config['sess_table_name']		= 'ci_sessions';
$config['sess_match_ip']		= TRUE;
$config['sess_match_useragent']	= TRUE;
$config['sess_time_to_update']	= 300;

/*
|--------------------------------------------------------------------------
| Cookie Related Variables
|--------------------------------------------------------------------------
|
| 'cookie_prefix' = Set a prefix if you need to avoid collisions
| 'cookie_domain' = Set to .your-domain.com for site-wide cookies
| 'cookie_path'   =  Typically will be a forward slash
| 'cookie_secure' =  Cookies will only be set if a secure HTTPS connection exists.
|
*/
$config['cookie_prefix']	= "hms_";
$config['cookie_domain']	= "";
$config['cookie_path']		= "/";
// IMPORTANT:
// CI's CSRF protection stores the token in a cookie. If cookie_secure is TRUE
// on a plain HTTP site, the browser won't accept/send the CSRF cookie and all
// POSTs (except csrf_exclude_uris) will fail with:
//   "The action you have requested is not allowed."
//
// We therefore set cookie_secure based on the *actual request scheme*, not the
// environment name. This keeps production-on-HTTP (common on LAN setups) working,
// while still enabling Secure cookies automatically when HTTPS is used.
$isHttpsCookie = (
	(!empty($_SERVER['HTTPS']) && strtolower($_SERVER['HTTPS']) !== 'off')
	|| (!empty($_SERVER['HTTP_X_FORWARDED_PROTO']) && strtolower($_SERVER['HTTP_X_FORWARDED_PROTO']) === 'https')
	|| (!empty($_SERVER['SERVER_PORT']) && (int)$_SERVER['SERVER_PORT'] === 443)
);
$config['cookie_secure']	= $isHttpsCookie;
$config['cookie_httponly']	= TRUE;

/*
|--------------------------------------------------------------------------
| Global XSS Filtering
|--------------------------------------------------------------------------
|
| Determines whether the XSS filter is always active when GET, POST or
| COOKIE data is encountered
|
*/
$config['global_xss_filtering'] = TRUE;

/*
|--------------------------------------------------------------------------
| Cross Site Request Forgery
|--------------------------------------------------------------------------
| Enables a CSRF cookie token to be set. When set to TRUE, token will be
| checked on a submitted form. If you are accepting user data, it is strongly
| recommended CSRF protection be enabled.
|
| 'csrf_token_name' = The token name
| 'csrf_cookie_name' = The cookie name
| 'csrf_expire' = The number in seconds the token should expire.
*/
$config['csrf_protection'] = TRUE;
$config['csrf_token_name'] = 'hms_csrf_token';
$config['csrf_cookie_name'] = 'csrf_cookie';
$config['csrf_expire'] = 7200;
$config['csrf_regenerate'] = FALSE;
$config['csrf_exclude_uris'] = array(
	'nhis_mock_api/.*',
	'login',
	'login/validate_login',
	'login/index',
	
);

/*
|--------------------------------------------------------------------------
| Output Compression
|--------------------------------------------------------------------------
|
| Enables Gzip output compression for faster page loads.  When enabled,
| the output class will test whether your server supports Gzip.
| Even if it does, however, not all browsers support compression
| so enable only if you are reasonably sure your visitors can handle it.
|
| VERY IMPORTANT:  If you are getting a blank page when compression is enabled it
| means you are prematurely outputting something to your browser. It could
| even be a line of whitespace at the end of one of your scripts.  For
| compression to work, nothing can be sent before the output buffer is called
| by the output class.  Do not 'echo' any values with compression enabled.
|
*/
$config['compress_output'] = FALSE;

/*
|--------------------------------------------------------------------------
| Master Time Reference
|--------------------------------------------------------------------------
|
| Options are 'local' or 'gmt'.  This pref tells the system whether to use
| your server's local time as the master 'now' reference, or convert it to
| GMT.  See the 'date helper' page of the user guide for information
| regarding date handling.
|
*/
$config['time_reference'] = 'local';


/*
|--------------------------------------------------------------------------
| Rewrite PHP Short Tags
|--------------------------------------------------------------------------
|
| If your PHP installation does not have short tag support enabled CI
| can rewrite the tags on-the-fly, enabling you to utilize that syntax
| in your view files.  Options are TRUE or FALSE (boolean)
|
*/
$config['rewrite_short_tags'] = FALSE;


/*
|--------------------------------------------------------------------------
| Reverse Proxy IPs
|--------------------------------------------------------------------------
|
| If your server is behind a reverse proxy, you must whitelist the proxy IP
| addresses from which CodeIgniter should trust the HTTP_X_FORWARDED_FOR
| header in order to properly identify the visitor's IP address.
| Comma-delimited, e.g. '10.0.1.200,10.0.1.201'
|
*/
$config['proxy_ips'] = '127.0.0.1, ::1';


/*
|--------------------------------------------------------------------------
| SSOT Feature Flags (Phase 4 — Billing consolidation)
|--------------------------------------------------------------------------
|
| BILLING_FACADE_RECEIPT_ROUTE
|   When TRUE, the four legacy receipt-recording sites
|     - cashier_model::process_payment()
|     - billing_model::record_payment()
|     - unified_billing_model::process_payment()
|     - controllers/app/pos.php::save_payment()
|   delegate to Billing_facade_model::record_payment(), the canonical
|   chokepoint that owns the union of receipt side-effects (insert,
|   header balance update, cashier_payment_log, financial audit,
|   double-entry ledger, billing_transactions SSOT sync, gate release).
|
|   Default: FALSE (Step 4 ships dark — zero behavior change).
|   Flip to TRUE when ready to validate consolidated receipt path.
|   May also be toggled at runtime via the BILLING_FACADE_RECEIPT_ROUTE
|   environment variable (Apache SetEnv, .htaccess, etc.).
|
*/
$config['BILLING_FACADE_RECEIPT_ROUTE'] = TRUE;

/*
| BILLING_FACADE_STRICT_HEADER
|   Controls header/line invariant enforcement at invoice save time
|   (Billing_facade_model::save_invoice_from_post / update_invoice_from_post).
|
|   FALSE (default): if the submitted header total does not match
|     SUM(iop_billing_t.amount), the header is silently corrected
|     to the SSOT value (legacy behavior). Every check is now
|     audited as HEADER_LINE_CHECK or HEADER_LINE_MISMATCH in
|     billing_audit_log so mismatches are observable.
|
|   TRUE: a mismatch rolls back the save and returns an error to
|     the caller. The user sees a clear failure flash. Use this
|     once you've confirmed (via the audit table) that mismatches
|     are rare or zero in practice.
*/
$config['BILLING_FACADE_STRICT_HEADER'] = FALSE;

/*
| BILLING_FACADE_NHIS_CLAIM_SSOT  (Step 7)
|   When TRUE, every NHIS claim generated by nhis_model::generate_claim
|   is cross-checked against billing_transactions (SSOT). If the claim's
|   computed NHIS or patient total disagrees with the SSOT by more than
|   GHS 0.01, the claim is rejected and the operator sees an error.
|   When FALSE (default), the mismatch is audited as
|   NHIS_CLAIM_TOTAL_MISMATCH but the claim still proceeds — identical
|   to pre-Step-7 behavior. Use the audit data to confirm zero
|   mismatches before flipping to TRUE.
*/
$config['BILLING_FACADE_NHIS_CLAIM_SSOT'] = FALSE;

/*
| BILLING_FACADE_COMPANY_PRICING_SWEEP  (Step 9)
|   When TRUE, every COMPANY-payer invoice saved through the facade
|   has its line items re-priced through Price_engine_model::resolve()
|   so the company's `pricing_percentage` applies uniformly to lab,
|   imaging, IPD room, OT, services, and drugs. Without this flag the
|   adjustment only happens for pharmacy items via the legacy
|   apply_company_pricing_to_pharmacy_items helper.
|   FALSE (default) preserves today's behavior. Adjustments, when
|   applied, are audited as COMPANY_PRICING_ADJUSTMENT.
*/
$config['BILLING_FACADE_COMPANY_PRICING_SWEEP'] = FALSE;

/*
| BILLING_FACADE_IMMUTABLE_AFTER_RECEIPT  (Step 10)
|   When TRUE, update_invoice_from_post() rejects any attempt to
|   edit an invoice that has at least one active receipt
|   (iop_receipt.InActive = 0). The user is told to void the
|   receipt first or use a separate adjustment workflow.
|   FALSE (default) only audits the attempt as
|   INVOICE_EDIT_AFTER_RECEIPT and lets the edit proceed.
*/
$config['BILLING_FACADE_IMMUTABLE_AFTER_RECEIPT'] = FALSE;

$config['drift_block_critical'] = FALSE;

// Shadow Governance — DISABLED for performance.
// Re-enable for auditing/debugging by setting to TRUE.
// When enabled, it instruments every DB query and runs post-request analysis.
$config['SHADOW_GOVERNANCE_ENABLED'] = FALSE;
$config['SHADOW_GOVERNANCE_REGISTRY_VERSION'] = 'V0';
$config['SHADOW_GOVERNANCE_LOG_DB_WRITES'] = FALSE;
$config['SHADOW_GOVERNANCE_LOG_CONTROLLER'] = FALSE;
$config['SHADOW_GOVERNANCE_LOG_DOMAIN_MAP'] = FALSE;

$config['SHADOW_GOVERNANCE_ENFORCEMENT_MODE'] = FALSE;

$config['partial_payment_threshold'] = 0.5;
$config['enforce_partial_threshold'] = FALSE;

$config['enforce_nhis_validation'] = FALSE;

$config['enforce_insurance_auth'] = FALSE;

$config['WALKIN_SUBJECT_BILLING'] = FALSE;
$config['WALKIN_ITEMREF_GATE'] = FALSE;
$config['WALKIN_PHARMACY_QUEUE'] = FALSE;
$config['WALKIN_LAB_QUEUE'] = FALSE;
$config['WALKIN_CUSTOM_PRICING'] = FALSE;
$config['WALKIN_COMPANY_CREDIT_POLICY'] = FALSE;

/* End of file config.php */
/* Location: ./application/config/config.php */
